version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped #will always try to restart the container db if it fails
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noxus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build:
      context: .
    command: ["pytest", "tests/"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/noxus_test
      - PYTHONPATH=/app

volumes:
  postgres_data: